### ISSUE TITLE
Sharing MishkinaMish

### ISSUE THREAD

**Issue by oneswitch** [MastaLomaster/mishkinamish#3]
I've posted a little on Mishkinamish. I wondered if it would be okay to share pre-configured versions of Mishkinamish on-line, with credit back to you?

[Blogger post on Mishkinamish](https://switchgaming.blogspot.com/2019/06/mishkinamish-voice-control.html)

This might help people who can't speak Russian. Hope this is okay.

Keep up the brilliant work.

**Comment by MastaLomaster** [comment]
It was a big surprise for me to see your effort in making the guide in English for the program.
In turn, I will try to make an English interface for it... in reasonable time.
Sure you can share whatever you want. Unfortunately the pre-configured versions make no sense as the program is very speaker-sensitive. Even more, it's microphone-sensitive. That means that if you change a microphone, you will have to re-train the program.
That is something I can't change due to the limits of the technology chosen, and that's why I think you've overestimated the program.

**Comment by oneswitch** [comment]
Thank you for getting back, and apologies for my lack of Russian. To make an English version would be so helpful. Thank you!

I thought it might help non-English users to have a few examples, only needing to train them, to see what's possible. With an option to translate to English, this will be less useful. Thanks for explaining more on how it works and is tied into specific users and microphones. It's still a brilliant bit of software you've made.

I still don't really understand what this means, as Google Translate doesn't really make it clear to me:

![image](https://user-images.githubusercontent.com/9967089/58784493-793ec680-85db-11e9-84c2-ca123ec892d1.png)

**Comment by MastaLomaster** [comment]
The English version is ready, just download the "mishkinamish-English.exe" file.
There, I translated the phrase you screenshoted as "Do not react on “K” and “Ch” when they are inside a word. Draw a red square if there was no silence before/after them"

This was done to eliminate false mouse clicks when a user needs to speak while the program is active. If the "K" or "Ch" sound is not standalone, but is a part of a speech, the program tries to suppress it. This doesn't work well all the time, however.

**Comment by MastaLomaster** [comment]
I also included your English guide into the "Readme" (slightly changed). If you don't mind.

**Comment by oneswitch** [comment]
I don't mind at all, you're very welcome.

Thanks for the extra explanation. The "draw a red square" confused me, but I understand it now. I've posted some English changes that you may like to consider.
